FROM ubuntu:xenial-20180228
RUN sed -i s:archive.ubuntu.com:mirrors.aliyun.com:g /etc/apt/sources.list
RUN apt-get update && apt-get install -y golang-1.10-go clang-5.0
RUN ln -s /usr/lib/go-1.10/bin/go /usr/bin/go && ln -s /usr/bin/clang-5.0 /usr/bin/clang
