#!/usr/bin/env bash
set -ex
GOOS=linux go install qiniu.com/argus/AIProjects/tianyan/app/video-stream-backend
cp -r $QBOXROOT/bin/video-stream-backend .
cp $QBOXROOT/src/qiniu.com/argus/AIProjects/tianyan/app/video-stream-backend/video-stream-backend.conf .
