argus-hack-watch: cd hack && exec ../../../../bin/argus-hack-watch -p 8558
image_group: cd hack && ENV=LOCAL CONFIG_HOSTS=localhost:2379 PORT_HTTP=8201 exec ../../../../bin/image_group -f ../cmd/image_group/image_group/image_group.conf
image_group_worker: cd hack && CONFIG_HOSTS=localhost:2379 PORT_HTTP=8202 exec ../../../../bin/image_group_worker -f ../cmd/image_group/image_group_worker/image_group_worker.conf
