# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: inference.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='inference.proto',
  package='inference',
  serialized_pb='\n\x0finference.proto\x12\tinference\"\x19\n\nInitParams\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\"\xc7\x02\n\x0c\x43reateParams\x12\x17\n\nuse_device\x18\x01 \x01(\t:\x03GPU\x12\x15\n\nbatch_size\x18\x02 \x01(\x05:\x01\x31\x12(\n\x03\x65nv\x18\x04 \x01(\x0b\x32\x1b.inference.CreateParams.Env\x12\x31\n\x0bmodel_files\x18\t \x03(\x0b\x32\x1c.inference.CreateParams.File\x12\x14\n\x0cmodel_params\x18\n \x01(\t\x12\x32\n\x0c\x63ustom_files\x18\x0b \x03(\x0b\x32\x1c.inference.CreateParams.File\x12\x15\n\rcustom_params\x18\x0c \x01(\t\x1a%\n\x03\x45nv\x12\x0b\n\x03\x61pp\x18\x01 \x01(\t\x12\x11\n\tworkspace\x18\x02 \x01(\t\x1a\"\n\x04\x46ile\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0c\n\x04\x62ody\x18\x02 \x01(\x0c\"\xce\x01\n\x10InferenceRequest\x12\x35\n\x04\x64\x61ta\x18\x01 \x01(\x0b\x32\'.inference.InferenceRequest.RequestData\x12\x36\n\x05\x64\x61tas\x18\x02 \x03(\x0b\x32\'.inference.InferenceRequest.RequestData\x12\x0e\n\x06params\x18\x03 \x01(\t\x1a;\n\x0bRequestData\x12\x0b\n\x03uri\x18\x01 \x01(\t\x12\x11\n\tattribute\x18\x02 \x01(\t\x12\x0c\n\x04\x62ody\x18\x03 \x01(\x0c\"B\n\x11InferenceRequests\x12-\n\x08requests\x18\x01 \x03(\x0b\x32\x1b.inference.InferenceRequest\"P\n\x11InferenceResponse\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x0e\n\x06result\x18\x05 \x01(\t\x12\x0c\n\x04\x62ody\x18\x06 \x01(\x0c\"E\n\x12InferenceResponses\x12/\n\tresponses\x18\x01 \x03(\x0b\x32\x1c.inference.InferenceResponse')




_INITPARAMS = _descriptor.Descriptor(
  name='InitParams',
  full_name='inference.InitParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app', full_name='inference.InitParams.app', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=30,
  serialized_end=55,
)


_CREATEPARAMS_ENV = _descriptor.Descriptor(
  name='Env',
  full_name='inference.CreateParams.Env',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='app', full_name='inference.CreateParams.Env.app', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='workspace', full_name='inference.CreateParams.Env.workspace', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=312,
  serialized_end=349,
)

_CREATEPARAMS_FILE = _descriptor.Descriptor(
  name='File',
  full_name='inference.CreateParams.File',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='inference.CreateParams.File.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='inference.CreateParams.File.body', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=351,
  serialized_end=385,
)

_CREATEPARAMS = _descriptor.Descriptor(
  name='CreateParams',
  full_name='inference.CreateParams',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='use_device', full_name='inference.CreateParams.use_device', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=True, default_value=unicode("GPU", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='batch_size', full_name='inference.CreateParams.batch_size', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='env', full_name='inference.CreateParams.env', index=2,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_files', full_name='inference.CreateParams.model_files', index=3,
      number=9, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='model_params', full_name='inference.CreateParams.model_params', index=4,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_files', full_name='inference.CreateParams.custom_files', index=5,
      number=11, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='custom_params', full_name='inference.CreateParams.custom_params', index=6,
      number=12, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_CREATEPARAMS_ENV, _CREATEPARAMS_FILE, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=58,
  serialized_end=385,
)


_INFERENCEREQUEST_REQUESTDATA = _descriptor.Descriptor(
  name='RequestData',
  full_name='inference.InferenceRequest.RequestData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='uri', full_name='inference.InferenceRequest.RequestData.uri', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='attribute', full_name='inference.InferenceRequest.RequestData.attribute', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='inference.InferenceRequest.RequestData.body', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=535,
  serialized_end=594,
)

_INFERENCEREQUEST = _descriptor.Descriptor(
  name='InferenceRequest',
  full_name='inference.InferenceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='inference.InferenceRequest.data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='datas', full_name='inference.InferenceRequest.datas', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='params', full_name='inference.InferenceRequest.params', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_INFERENCEREQUEST_REQUESTDATA, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=388,
  serialized_end=594,
)


_INFERENCEREQUESTS = _descriptor.Descriptor(
  name='InferenceRequests',
  full_name='inference.InferenceRequests',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='requests', full_name='inference.InferenceRequests.requests', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=596,
  serialized_end=662,
)


_INFERENCERESPONSE = _descriptor.Descriptor(
  name='InferenceResponse',
  full_name='inference.InferenceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='inference.InferenceResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='message', full_name='inference.InferenceResponse.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='result', full_name='inference.InferenceResponse.result', index=2,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='body', full_name='inference.InferenceResponse.body', index=3,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value="",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=664,
  serialized_end=744,
)


_INFERENCERESPONSES = _descriptor.Descriptor(
  name='InferenceResponses',
  full_name='inference.InferenceResponses',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='responses', full_name='inference.InferenceResponses.responses', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=746,
  serialized_end=815,
)

_CREATEPARAMS_ENV.containing_type = _CREATEPARAMS;
_CREATEPARAMS_FILE.containing_type = _CREATEPARAMS;
_CREATEPARAMS.fields_by_name['env'].message_type = _CREATEPARAMS_ENV
_CREATEPARAMS.fields_by_name['model_files'].message_type = _CREATEPARAMS_FILE
_CREATEPARAMS.fields_by_name['custom_files'].message_type = _CREATEPARAMS_FILE
_INFERENCEREQUEST_REQUESTDATA.containing_type = _INFERENCEREQUEST;
_INFERENCEREQUEST.fields_by_name['data'].message_type = _INFERENCEREQUEST_REQUESTDATA
_INFERENCEREQUEST.fields_by_name['datas'].message_type = _INFERENCEREQUEST_REQUESTDATA
_INFERENCEREQUESTS.fields_by_name['requests'].message_type = _INFERENCEREQUEST
_INFERENCERESPONSES.fields_by_name['responses'].message_type = _INFERENCERESPONSE
DESCRIPTOR.message_types_by_name['InitParams'] = _INITPARAMS
DESCRIPTOR.message_types_by_name['CreateParams'] = _CREATEPARAMS
DESCRIPTOR.message_types_by_name['InferenceRequest'] = _INFERENCEREQUEST
DESCRIPTOR.message_types_by_name['InferenceRequests'] = _INFERENCEREQUESTS
DESCRIPTOR.message_types_by_name['InferenceResponse'] = _INFERENCERESPONSE
DESCRIPTOR.message_types_by_name['InferenceResponses'] = _INFERENCERESPONSES

class InitParams(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INITPARAMS

  # @@protoc_insertion_point(class_scope:inference.InitParams)

class CreateParams(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class Env(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CREATEPARAMS_ENV

    # @@protoc_insertion_point(class_scope:inference.CreateParams.Env)

  class File(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _CREATEPARAMS_FILE

    # @@protoc_insertion_point(class_scope:inference.CreateParams.File)
  DESCRIPTOR = _CREATEPARAMS

  # @@protoc_insertion_point(class_scope:inference.CreateParams)

class InferenceRequest(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType

  class RequestData(_message.Message):
    __metaclass__ = _reflection.GeneratedProtocolMessageType
    DESCRIPTOR = _INFERENCEREQUEST_REQUESTDATA

    # @@protoc_insertion_point(class_scope:inference.InferenceRequest.RequestData)
  DESCRIPTOR = _INFERENCEREQUEST

  # @@protoc_insertion_point(class_scope:inference.InferenceRequest)

class InferenceRequests(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INFERENCEREQUESTS

  # @@protoc_insertion_point(class_scope:inference.InferenceRequests)

class InferenceResponse(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INFERENCERESPONSE

  # @@protoc_insertion_point(class_scope:inference.InferenceResponse)

class InferenceResponses(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _INFERENCERESPONSES

  # @@protoc_insertion_point(class_scope:inference.InferenceResponses)


# @@protoc_insertion_point(module_scope)
