#!/usr/bin/env bash
set -ex

rm -rf evals
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/evals .
cp $QBOXROOT/ataraxia/inference/ocr/scene/textidentify/src/main.py evals/eval.py

#ln /dev/null /dev/raw1394

rm -rf src
cp -r $QBOXROOT/ataraxia/inference/ocr/scene/textidentify/src src/

rm -rf build
mkdir build
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/inference/py build/
