// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/inference_api/classify.md
// DO NOT EDIT!

package client

type SceneReq struct {
	Data SceneReq_sub1 `json:"data"`
}

type SceneReq_sub1 struct {
	URI string `json:"uri"`
}
