// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/inference_api/facex.md
// DO NOT EDIT!

package client

type FacexClusterResp struct {
	Code    int64                 `json:"code"`
	Result  FacexClusterResp_sub1 `json:"result"`
	Message string                `json:"message"`
}
type FacexClusterResp_sub1 struct {
	FacexCluster []FacexClusterResp_sub2 `json:"facex_cluster"`
}
type FacexClusterResp_sub2 struct {
	ClusterCenterDist float64 `json:"cluster_center_dist"`
	ClusterID         int64   `json:"cluster_id"`
}
