// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/inference_api/facex.md
// DO NOT EDIT!

package client

type FacexFeatureReq struct {
	Data struct {
		URI       string `json:"uri"`
		Attribute struct {
			Pts [][]int64 `json:"pts"`
		} `json:"attribute"`
	} `json:"data"`
}
