// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/inference_api/facex.md
// DO NOT EDIT!

package client

type FacexDetResp struct {
	Code    int64             `json:"code"`
	Result  FacexDetResp_sub2 `json:"result"`
	Message string            `json:"message"`
}

type FacexDetResp_sub1 struct {
	Index int       `json:"index"`
	Class string    `json:"class"`
	Pts   [][]int64 `json:"pts"`
	Score float64   `json:"score"`
}

type FacexDetResp_sub2 struct {
	Detections []FacexDetResp_sub1 `json:"detections"`
}
