// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/inference_api/facex.md
// DO NOT EDIT!

package client

type FacexDetReq struct {
	Data struct {
		URI string `json:"uri"`
	} `json:"data"`
}
