// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/inference_api/facex.md
// DO NOT EDIT!

package client

type FacexClusterReq struct {
	Data []FacexClusterReq_sub1 `json:"data"`
}

type FacexClusterReq_sub1 struct {
	URI       string               `json:"uri"`
	Attribute FacexClusterReq_sub2 `json:"attribute"`
}

type FacexClusterReq_sub2 struct {
	ClusterID int64 `json:"cluster_id"`
	GtID      int64 `json:"gt_id"`
}
