#!/usr/bin/env bash
set -ex

rm -rf evals
cp -r $ATARAXIAROOT/ava/atserving/scripts/evals .
cp $ATARAXIAROOT/inference/ocr/idcard-pytorch/python/pytorch_ocr_idcard.py evals/eval.py
cp -r $ATARAXIAROOT/inference/ocr/idcard-pytorch/python evals/pytorch_idcard

rm -rf build
mkdir build
cp -r $ATARAXIAROOT/ava/atserving/scripts/inference/py build/py_eval
