#!/usr/bin/env bash
set -ex
go install qiniu.com/argus/cmd/argus-jobs/inference-image-worker
cp $QBOXROOT/bin/inference-image-worker .
cp $QBOXROOT/src/qiniu.com/argus/cmd/argus-jobs/inference-image-worker/inference-image-worker.conf .
