
# NUM_CLASSES: 1
INPUT_SHAPE: [3, 224, 224]
MEAN_RGB: [123.68, 116.779, 103.939]
STD_RGB: [58.395, 57.12, 57.375]

TRAIN:
  LOG_PATH: .
  BATCH_SIZE: 64
  # GPU_IDX: []
  LOG_INTERVAL: 80
  # NUM_SAMPLES: 1
  ITER:
    preprocess_threads: 4
  TRAIN_ITER:
    path_imgrec: xxx.rec
  DEV_ITER:
    path_imgrec: xxx.rec
  FINETUNE:
    PRETRAINED_MODEL_PREFIX: xxx
    PRETRAINED_MODEL_EPOCH: 0
    FINETUNE_LAYER: flatten0
  SOFTMAX_SMOOTH_ALPHA: 0.01
  OUTPUT_MODEL_PREFIX: xxx
  MAX_EPOCHS: 70
  # BASE_LR: 0.0
  # MOMENTUM: 0.9
  # WEIGHT_DECAY: 0.0001
