#!/usr/bin/env bash
set -ex
rm -rf evals
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/evals .
cp $QBOXROOT/ataraxia/inference/terror/python/terror-postdetect/terror-postdetect-refinedet.py evals/eval.py

rm -rf build
mkdir build
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/inference/py build/