// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_post_images_facegroups_adjust.md
// DO NOT EDIT!

package proto

type PostImagesFacegroupsAdjustReq struct {
	Euid        string   `json:"euid"`
	FromGroupID int64    `json:"from_group_id"`
	Items       []string `json:"items"`
	ToGroupID   int64    `json:"to_group_id"`
}
