// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_post_images_facegroups.md
// DO NOT EDIT!

package proto

type PostImagesFacegroupsResp struct {
	Message string                        `json:"message"`
	Modelv  string                        `json:"modelv"`
	Result  PostImagesFacegroupsResp_sub2 `json:"result"`
}

type PostImagesFacegroupsResp_sub1 struct {
	Code    int64  `json:"code"`
	Item    string `json:"item"`
	Message string `json:"message"`
}

type PostImagesFacegroupsResp_sub2 struct {
	Fail []PostImagesFacegroupsResp_sub1 `json:"fail"`
}
