// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_post_images_scene.md
// DO NOT EDIT!

package proto

type PostImagesSceneResp struct {
	Message string                   `json:"message"`
	Modelv  string                   `json:"modelv"`
	Result  PostImagesSceneResp_sub3 `json:"result"`
}

type PostImagesSceneResp_sub1 struct {
	Code    int64  `json:"code"`
	Item    string `json:"item"`
	Message string `json:"message"`
}

type PostImagesSceneResp_sub3 struct {
	Fail    []PostImagesSceneResp_sub1 `json:"fail"`
	Success []PostImagesSceneResp_sub2 `json:"success"`
}

type PostImagesSceneResp_sub2 struct {
	Item  string `json:"item"`
	Scene string `json:"scene"`
}
