// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_post_images_objects.md
// DO NOT EDIT!

package proto

type PostImagesObjectsResp struct {
	Message string                     `json:"message"`
	Modelv  string                     `json:"modelv"`
	Result  PostImagesObjectsResp_sub4 `json:"result"`
}

type PostImagesObjectsResp_sub2 struct {
	Class string    `json:"class"`
	Pts   [][]int64 `json:"pts"`
	Score float64   `json:"score"`
}

type PostImagesObjectsResp_sub1 struct {
	Code    int64  `json:"code"`
	Item    string `json:"item"`
	Message string `json:"message"`
}

type PostImagesObjectsResp_sub4 struct {
	Fail    []PostImagesObjectsResp_sub1 `json:"fail"`
	Success []PostImagesObjectsResp_sub3 `json:"success"`
}

type PostImagesObjectsResp_sub3 struct {
	Item    string                       `json:"item"`
	Objects []PostImagesObjectsResp_sub2 `json:"objects"`
}
