// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_post_images_facegroups_merge.md
// DO NOT EDIT!

package proto

type PostImagesFacegroupsMergeReq struct {
	Euid      string  `json:"euid"`
	Groups    []int64 `json:"groups"`
	ToGroupID int64   `json:"to_group_id"`
}
