// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_post_images_scene.md
// DO NOT EDIT!

package proto

type PostImagesScenerecResp struct {
	Message string                      `json:"message"`
	Modelv  string                      `json:"modelv"`
	Result  PostImagesScenerecResp_sub4 `json:"result"`
}

type PostImagesScenerecResp_sub2 struct {
	Class []string `json:"class"`
	Score float64  `json:"score"`
}

type PostImagesScenerecResp_sub1 struct {
	Code    int64  `json:"code"`
	Item    string `json:"item"`
	Message string `json:"message"`
}

type PostImagesScenerecResp_sub4 struct {
	Fail    []PostImagesScenerecResp_sub1 `json:"fail"`
	Success []PostImagesScenerecResp_sub3 `json:"success"`
}

type PostImagesScenerecResp_sub3 struct {
	Item string                        `json:"item"`
	Top  []PostImagesScenerecResp_sub2 `json:"top"`
}
