// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_post_images_scene.md
// DO NOT EDIT!

package proto

type PostImagesScenerecReq struct {
	Euid  string   `json:"euid"`
	Items []string `json:"items"`
}
