// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_get_images_facegroups_id.md
// DO NOT EDIT!

package proto

type GetImagesFacegroupsIDResp struct {
	Faces   []GetImagesFacegroupsIDResp_sub1 `json:"faces"`
	Message string                           `json:"message"`
	Modelv  string                           `json:"modelv"`
}

type GetImagesFacegroupsIDResp_sub1 struct {
	URI   string    `json:"uri"`
	Pts   [][]int64 `json:"pts"`
	Score float64   `json:"score"`
}
