// Code generated by make gen.
// source: ./platform/src/qiniu.com/argus/argus/docs/argus/apis/api_get_images_facegroups.md
// DO NOT EDIT!

package proto

type GetImagesFacegroupsResp struct {
	Groups  []GetImagesFacegroupsResp_sub2 `json:"groups"`
	Message string                         `json:"message"`
	Modelv  string                         `json:"modelv"`
}

type GetImagesFacegroupsResp_sub2 struct {
	FaceCount int64                            `json:"face_count"`
	ID        int64                            `json:"id"`
	Refs      []GetImagesFacegroupsResp_sub1   `json:"refs,omitempty"`
	Faces     []GetImagesFacegroupsIDResp_sub1 `json:"faces"`
}

type GetImagesFacegroupsResp_sub1 struct {
	File  string    `json:"file"`
	Pts   [][]int64 `json:"pts"`
	Score float64   `json:"score"`
}
