// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: forward.proto

#include "forward.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_forward_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_forward_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ForwardRequest_Data;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_forward_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ForwardResponse_Box;
extern PROTOBUF_INTERNAL_EXPORT_protobuf_forward_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_ForwardResponse_Label;
}  // namespace protobuf_forward_2eproto
namespace inference {
namespace wa {
class ForwardRequest_DataDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ForwardRequest_Data>
      _instance;
} _ForwardRequest_Data_default_instance_;
class ForwardRequestDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ForwardRequest>
      _instance;
} _ForwardRequest_default_instance_;
class ForwardResponse_BoxDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ForwardResponse_Box>
      _instance;
} _ForwardResponse_Box_default_instance_;
class ForwardResponse_LabelDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ForwardResponse_Label>
      _instance;
} _ForwardResponse_Label_default_instance_;
class ForwardResponseDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<ForwardResponse>
      _instance;
} _ForwardResponse_default_instance_;
}  // namespace wa
}  // namespace inference
namespace protobuf_forward_2eproto {
static void InitDefaultsForwardRequest_Data() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::wa::_ForwardRequest_Data_default_instance_;
    new (ptr) ::inference::wa::ForwardRequest_Data();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::wa::ForwardRequest_Data::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ForwardRequest_Data =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsForwardRequest_Data}, {}};

static void InitDefaultsForwardRequest() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::wa::_ForwardRequest_default_instance_;
    new (ptr) ::inference::wa::ForwardRequest();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::wa::ForwardRequest::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_ForwardRequest =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsForwardRequest}, {
      &protobuf_forward_2eproto::scc_info_ForwardRequest_Data.base,}};

static void InitDefaultsForwardResponse_Box() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::wa::_ForwardResponse_Box_default_instance_;
    new (ptr) ::inference::wa::ForwardResponse_Box();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::wa::ForwardResponse_Box::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ForwardResponse_Box =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsForwardResponse_Box}, {}};

static void InitDefaultsForwardResponse_Label() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::wa::_ForwardResponse_Label_default_instance_;
    new (ptr) ::inference::wa::ForwardResponse_Label();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::wa::ForwardResponse_Label::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_ForwardResponse_Label =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsForwardResponse_Label}, {}};

static void InitDefaultsForwardResponse() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::inference::wa::_ForwardResponse_default_instance_;
    new (ptr) ::inference::wa::ForwardResponse();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::inference::wa::ForwardResponse::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<2> scc_info_ForwardResponse =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 2, InitDefaultsForwardResponse}, {
      &protobuf_forward_2eproto::scc_info_ForwardResponse_Box.base,
      &protobuf_forward_2eproto::scc_info_ForwardResponse_Label.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_ForwardRequest_Data.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ForwardRequest.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ForwardResponse_Box.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ForwardResponse_Label.base);
  ::google::protobuf::internal::InitSCC(&scc_info_ForwardResponse.base);
}

::google::protobuf::Metadata file_level_metadata[5];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardRequest_Data, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardRequest_Data, body_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardRequest, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardRequest, data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardRequest, h_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardRequest, w_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Box, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Box, xmin_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Box, ymin_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Box, xmax_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Box, ymax_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Box, score_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Box, label_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Label, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Label, index_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse_Label, score_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse, code_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse, message_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse, boxes_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::inference::wa::ForwardResponse, label_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::inference::wa::ForwardRequest_Data)},
  { 6, -1, sizeof(::inference::wa::ForwardRequest)},
  { 14, -1, sizeof(::inference::wa::ForwardResponse_Box)},
  { 25, -1, sizeof(::inference::wa::ForwardResponse_Label)},
  { 32, -1, sizeof(::inference::wa::ForwardResponse)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::wa::_ForwardRequest_Data_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::wa::_ForwardRequest_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::wa::_ForwardResponse_Box_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::wa::_ForwardResponse_Label_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::inference::wa::_ForwardResponse_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "forward.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 5);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\rforward.proto\022\014inference.wa\"m\n\016Forward"
      "Request\022/\n\004data\030\001 \001(\0132!.inference.wa.For"
      "wardRequest.Data\022\t\n\001h\030\005 \001(\005\022\t\n\001w\030\006 \001(\005\032\024"
      "\n\004Data\022\014\n\004body\030\003 \001(\014\"\232\002\n\017ForwardResponse"
      "\022\014\n\004code\030\001 \001(\005\022\017\n\007message\030\002 \001(\t\0220\n\005boxes"
      "\030\005 \003(\0132!.inference.wa.ForwardResponse.Bo"
      "x\0222\n\005label\030\006 \003(\0132#.inference.wa.ForwardR"
      "esponse.Label\032[\n\003Box\022\014\n\004xmin\030\001 \001(\002\022\014\n\004ym"
      "in\030\002 \001(\002\022\014\n\004xmax\030\003 \001(\002\022\014\n\004ymax\030\004 \001(\002\022\r\n\005"
      "score\030\005 \001(\002\022\r\n\005label\030\006 \001(\005\032%\n\005Label\022\r\n\005i"
      "ndex\030\001 \001(\005\022\r\n\005score\030\002 \001(\002b\006proto3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 433);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "forward.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_forward_2eproto
namespace inference {
namespace wa {

// ===================================================================

void ForwardRequest_Data::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ForwardRequest_Data::kBodyFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ForwardRequest_Data::ForwardRequest_Data()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_forward_2eproto::scc_info_ForwardRequest_Data.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.wa.ForwardRequest.Data)
}
ForwardRequest_Data::ForwardRequest_Data(const ForwardRequest_Data& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.body().size() > 0) {
    body_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
  // @@protoc_insertion_point(copy_constructor:inference.wa.ForwardRequest.Data)
}

void ForwardRequest_Data::SharedCtor() {
  body_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

ForwardRequest_Data::~ForwardRequest_Data() {
  // @@protoc_insertion_point(destructor:inference.wa.ForwardRequest.Data)
  SharedDtor();
}

void ForwardRequest_Data::SharedDtor() {
  body_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ForwardRequest_Data::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ForwardRequest_Data::descriptor() {
  ::protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ForwardRequest_Data& ForwardRequest_Data::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_forward_2eproto::scc_info_ForwardRequest_Data.base);
  return *internal_default_instance();
}


void ForwardRequest_Data::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.wa.ForwardRequest.Data)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  body_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool ForwardRequest_Data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.wa.ForwardRequest.Data)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // bytes body = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_body()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.wa.ForwardRequest.Data)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.wa.ForwardRequest.Data)
  return false;
#undef DO_
}

void ForwardRequest_Data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.wa.ForwardRequest.Data)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes body = 3;
  if (this->body().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      3, this->body(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.wa.ForwardRequest.Data)
}

::google::protobuf::uint8* ForwardRequest_Data::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.wa.ForwardRequest.Data)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // bytes body = 3;
  if (this->body().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        3, this->body(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.wa.ForwardRequest.Data)
  return target;
}

size_t ForwardRequest_Data::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.wa.ForwardRequest.Data)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // bytes body = 3;
  if (this->body().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->body());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ForwardRequest_Data::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.wa.ForwardRequest.Data)
  GOOGLE_DCHECK_NE(&from, this);
  const ForwardRequest_Data* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ForwardRequest_Data>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.wa.ForwardRequest.Data)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.wa.ForwardRequest.Data)
    MergeFrom(*source);
  }
}

void ForwardRequest_Data::MergeFrom(const ForwardRequest_Data& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.wa.ForwardRequest.Data)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.body().size() > 0) {

    body_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.body_);
  }
}

void ForwardRequest_Data::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.wa.ForwardRequest.Data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ForwardRequest_Data::CopyFrom(const ForwardRequest_Data& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.wa.ForwardRequest.Data)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForwardRequest_Data::IsInitialized() const {
  return true;
}

void ForwardRequest_Data::Swap(ForwardRequest_Data* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ForwardRequest_Data::InternalSwap(ForwardRequest_Data* other) {
  using std::swap;
  body_.Swap(&other->body_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ForwardRequest_Data::GetMetadata() const {
  protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ForwardRequest::InitAsDefaultInstance() {
  ::inference::wa::_ForwardRequest_default_instance_._instance.get_mutable()->data_ = const_cast< ::inference::wa::ForwardRequest_Data*>(
      ::inference::wa::ForwardRequest_Data::internal_default_instance());
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ForwardRequest::kDataFieldNumber;
const int ForwardRequest::kHFieldNumber;
const int ForwardRequest::kWFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ForwardRequest::ForwardRequest()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_forward_2eproto::scc_info_ForwardRequest.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.wa.ForwardRequest)
}
ForwardRequest::ForwardRequest(const ForwardRequest& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  if (from.has_data()) {
    data_ = new ::inference::wa::ForwardRequest_Data(*from.data_);
  } else {
    data_ = NULL;
  }
  ::memcpy(&h_, &from.h_,
    static_cast<size_t>(reinterpret_cast<char*>(&w_) -
    reinterpret_cast<char*>(&h_)) + sizeof(w_));
  // @@protoc_insertion_point(copy_constructor:inference.wa.ForwardRequest)
}

void ForwardRequest::SharedCtor() {
  ::memset(&data_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&w_) -
      reinterpret_cast<char*>(&data_)) + sizeof(w_));
}

ForwardRequest::~ForwardRequest() {
  // @@protoc_insertion_point(destructor:inference.wa.ForwardRequest)
  SharedDtor();
}

void ForwardRequest::SharedDtor() {
  if (this != internal_default_instance()) delete data_;
}

void ForwardRequest::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ForwardRequest::descriptor() {
  ::protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ForwardRequest& ForwardRequest::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_forward_2eproto::scc_info_ForwardRequest.base);
  return *internal_default_instance();
}


void ForwardRequest::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.wa.ForwardRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  if (GetArenaNoVirtual() == NULL && data_ != NULL) {
    delete data_;
  }
  data_ = NULL;
  ::memset(&h_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&w_) -
      reinterpret_cast<char*>(&h_)) + sizeof(w_));
  _internal_metadata_.Clear();
}

bool ForwardRequest::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.wa.ForwardRequest)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .inference.wa.ForwardRequest.Data data = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_data()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 h = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(40u /* 40 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &h_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 w = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &w_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.wa.ForwardRequest)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.wa.ForwardRequest)
  return false;
#undef DO_
}

void ForwardRequest::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.wa.ForwardRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .inference.wa.ForwardRequest.Data data = 1;
  if (this->has_data()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_data(), output);
  }

  // int32 h = 5;
  if (this->h() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(5, this->h(), output);
  }

  // int32 w = 6;
  if (this->w() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->w(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.wa.ForwardRequest)
}

::google::protobuf::uint8* ForwardRequest::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.wa.ForwardRequest)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .inference.wa.ForwardRequest.Data data = 1;
  if (this->has_data()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_data(), deterministic, target);
  }

  // int32 h = 5;
  if (this->h() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(5, this->h(), target);
  }

  // int32 w = 6;
  if (this->w() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->w(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.wa.ForwardRequest)
  return target;
}

size_t ForwardRequest::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.wa.ForwardRequest)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // .inference.wa.ForwardRequest.Data data = 1;
  if (this->has_data()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *data_);
  }

  // int32 h = 5;
  if (this->h() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->h());
  }

  // int32 w = 6;
  if (this->w() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->w());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ForwardRequest::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.wa.ForwardRequest)
  GOOGLE_DCHECK_NE(&from, this);
  const ForwardRequest* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ForwardRequest>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.wa.ForwardRequest)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.wa.ForwardRequest)
    MergeFrom(*source);
  }
}

void ForwardRequest::MergeFrom(const ForwardRequest& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.wa.ForwardRequest)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.has_data()) {
    mutable_data()->::inference::wa::ForwardRequest_Data::MergeFrom(from.data());
  }
  if (from.h() != 0) {
    set_h(from.h());
  }
  if (from.w() != 0) {
    set_w(from.w());
  }
}

void ForwardRequest::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.wa.ForwardRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ForwardRequest::CopyFrom(const ForwardRequest& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.wa.ForwardRequest)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForwardRequest::IsInitialized() const {
  return true;
}

void ForwardRequest::Swap(ForwardRequest* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ForwardRequest::InternalSwap(ForwardRequest* other) {
  using std::swap;
  swap(data_, other->data_);
  swap(h_, other->h_);
  swap(w_, other->w_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ForwardRequest::GetMetadata() const {
  protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ForwardResponse_Box::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ForwardResponse_Box::kXminFieldNumber;
const int ForwardResponse_Box::kYminFieldNumber;
const int ForwardResponse_Box::kXmaxFieldNumber;
const int ForwardResponse_Box::kYmaxFieldNumber;
const int ForwardResponse_Box::kScoreFieldNumber;
const int ForwardResponse_Box::kLabelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ForwardResponse_Box::ForwardResponse_Box()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_forward_2eproto::scc_info_ForwardResponse_Box.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.wa.ForwardResponse.Box)
}
ForwardResponse_Box::ForwardResponse_Box(const ForwardResponse_Box& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&xmin_, &from.xmin_,
    static_cast<size_t>(reinterpret_cast<char*>(&label_) -
    reinterpret_cast<char*>(&xmin_)) + sizeof(label_));
  // @@protoc_insertion_point(copy_constructor:inference.wa.ForwardResponse.Box)
}

void ForwardResponse_Box::SharedCtor() {
  ::memset(&xmin_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&label_) -
      reinterpret_cast<char*>(&xmin_)) + sizeof(label_));
}

ForwardResponse_Box::~ForwardResponse_Box() {
  // @@protoc_insertion_point(destructor:inference.wa.ForwardResponse.Box)
  SharedDtor();
}

void ForwardResponse_Box::SharedDtor() {
}

void ForwardResponse_Box::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ForwardResponse_Box::descriptor() {
  ::protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ForwardResponse_Box& ForwardResponse_Box::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_forward_2eproto::scc_info_ForwardResponse_Box.base);
  return *internal_default_instance();
}


void ForwardResponse_Box::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.wa.ForwardResponse.Box)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&xmin_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&label_) -
      reinterpret_cast<char*>(&xmin_)) + sizeof(label_));
  _internal_metadata_.Clear();
}

bool ForwardResponse_Box::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.wa.ForwardResponse.Box)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // float xmin = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(13u /* 13 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &xmin_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float ymin = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &ymin_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float xmax = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(29u /* 29 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &xmax_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float ymax = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(37u /* 37 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &ymax_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float score = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(45u /* 45 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // int32 label = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(48u /* 48 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &label_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.wa.ForwardResponse.Box)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.wa.ForwardResponse.Box)
  return false;
#undef DO_
}

void ForwardResponse_Box::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.wa.ForwardResponse.Box)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float xmin = 1;
  if (this->xmin() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(1, this->xmin(), output);
  }

  // float ymin = 2;
  if (this->ymin() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->ymin(), output);
  }

  // float xmax = 3;
  if (this->xmax() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(3, this->xmax(), output);
  }

  // float ymax = 4;
  if (this->ymax() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(4, this->ymax(), output);
  }

  // float score = 5;
  if (this->score() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(5, this->score(), output);
  }

  // int32 label = 6;
  if (this->label() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(6, this->label(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.wa.ForwardResponse.Box)
}

::google::protobuf::uint8* ForwardResponse_Box::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.wa.ForwardResponse.Box)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // float xmin = 1;
  if (this->xmin() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(1, this->xmin(), target);
  }

  // float ymin = 2;
  if (this->ymin() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->ymin(), target);
  }

  // float xmax = 3;
  if (this->xmax() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(3, this->xmax(), target);
  }

  // float ymax = 4;
  if (this->ymax() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(4, this->ymax(), target);
  }

  // float score = 5;
  if (this->score() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(5, this->score(), target);
  }

  // int32 label = 6;
  if (this->label() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(6, this->label(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.wa.ForwardResponse.Box)
  return target;
}

size_t ForwardResponse_Box::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.wa.ForwardResponse.Box)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // float xmin = 1;
  if (this->xmin() != 0) {
    total_size += 1 + 4;
  }

  // float ymin = 2;
  if (this->ymin() != 0) {
    total_size += 1 + 4;
  }

  // float xmax = 3;
  if (this->xmax() != 0) {
    total_size += 1 + 4;
  }

  // float ymax = 4;
  if (this->ymax() != 0) {
    total_size += 1 + 4;
  }

  // float score = 5;
  if (this->score() != 0) {
    total_size += 1 + 4;
  }

  // int32 label = 6;
  if (this->label() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->label());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ForwardResponse_Box::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.wa.ForwardResponse.Box)
  GOOGLE_DCHECK_NE(&from, this);
  const ForwardResponse_Box* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ForwardResponse_Box>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.wa.ForwardResponse.Box)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.wa.ForwardResponse.Box)
    MergeFrom(*source);
  }
}

void ForwardResponse_Box::MergeFrom(const ForwardResponse_Box& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.wa.ForwardResponse.Box)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.xmin() != 0) {
    set_xmin(from.xmin());
  }
  if (from.ymin() != 0) {
    set_ymin(from.ymin());
  }
  if (from.xmax() != 0) {
    set_xmax(from.xmax());
  }
  if (from.ymax() != 0) {
    set_ymax(from.ymax());
  }
  if (from.score() != 0) {
    set_score(from.score());
  }
  if (from.label() != 0) {
    set_label(from.label());
  }
}

void ForwardResponse_Box::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.wa.ForwardResponse.Box)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ForwardResponse_Box::CopyFrom(const ForwardResponse_Box& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.wa.ForwardResponse.Box)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForwardResponse_Box::IsInitialized() const {
  return true;
}

void ForwardResponse_Box::Swap(ForwardResponse_Box* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ForwardResponse_Box::InternalSwap(ForwardResponse_Box* other) {
  using std::swap;
  swap(xmin_, other->xmin_);
  swap(ymin_, other->ymin_);
  swap(xmax_, other->xmax_);
  swap(ymax_, other->ymax_);
  swap(score_, other->score_);
  swap(label_, other->label_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ForwardResponse_Box::GetMetadata() const {
  protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ForwardResponse_Label::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ForwardResponse_Label::kIndexFieldNumber;
const int ForwardResponse_Label::kScoreFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ForwardResponse_Label::ForwardResponse_Label()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_forward_2eproto::scc_info_ForwardResponse_Label.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.wa.ForwardResponse.Label)
}
ForwardResponse_Label::ForwardResponse_Label(const ForwardResponse_Label& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::memcpy(&index_, &from.index_,
    static_cast<size_t>(reinterpret_cast<char*>(&score_) -
    reinterpret_cast<char*>(&index_)) + sizeof(score_));
  // @@protoc_insertion_point(copy_constructor:inference.wa.ForwardResponse.Label)
}

void ForwardResponse_Label::SharedCtor() {
  ::memset(&index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&score_) -
      reinterpret_cast<char*>(&index_)) + sizeof(score_));
}

ForwardResponse_Label::~ForwardResponse_Label() {
  // @@protoc_insertion_point(destructor:inference.wa.ForwardResponse.Label)
  SharedDtor();
}

void ForwardResponse_Label::SharedDtor() {
}

void ForwardResponse_Label::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ForwardResponse_Label::descriptor() {
  ::protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ForwardResponse_Label& ForwardResponse_Label::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_forward_2eproto::scc_info_ForwardResponse_Label.base);
  return *internal_default_instance();
}


void ForwardResponse_Label::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.wa.ForwardResponse.Label)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  ::memset(&index_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&score_) -
      reinterpret_cast<char*>(&index_)) + sizeof(score_));
  _internal_metadata_.Clear();
}

bool ForwardResponse_Label::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.wa.ForwardResponse.Label)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 index = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &index_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // float score = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(21u /* 21 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   float, ::google::protobuf::internal::WireFormatLite::TYPE_FLOAT>(
                 input, &score_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.wa.ForwardResponse.Label)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.wa.ForwardResponse.Label)
  return false;
#undef DO_
}

void ForwardResponse_Label::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.wa.ForwardResponse.Label)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 index = 1;
  if (this->index() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->index(), output);
  }

  // float score = 2;
  if (this->score() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteFloat(2, this->score(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.wa.ForwardResponse.Label)
}

::google::protobuf::uint8* ForwardResponse_Label::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.wa.ForwardResponse.Label)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 index = 1;
  if (this->index() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->index(), target);
  }

  // float score = 2;
  if (this->score() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteFloatToArray(2, this->score(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.wa.ForwardResponse.Label)
  return target;
}

size_t ForwardResponse_Label::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.wa.ForwardResponse.Label)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // int32 index = 1;
  if (this->index() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->index());
  }

  // float score = 2;
  if (this->score() != 0) {
    total_size += 1 + 4;
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ForwardResponse_Label::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.wa.ForwardResponse.Label)
  GOOGLE_DCHECK_NE(&from, this);
  const ForwardResponse_Label* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ForwardResponse_Label>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.wa.ForwardResponse.Label)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.wa.ForwardResponse.Label)
    MergeFrom(*source);
  }
}

void ForwardResponse_Label::MergeFrom(const ForwardResponse_Label& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.wa.ForwardResponse.Label)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.index() != 0) {
    set_index(from.index());
  }
  if (from.score() != 0) {
    set_score(from.score());
  }
}

void ForwardResponse_Label::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.wa.ForwardResponse.Label)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ForwardResponse_Label::CopyFrom(const ForwardResponse_Label& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.wa.ForwardResponse.Label)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForwardResponse_Label::IsInitialized() const {
  return true;
}

void ForwardResponse_Label::Swap(ForwardResponse_Label* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ForwardResponse_Label::InternalSwap(ForwardResponse_Label* other) {
  using std::swap;
  swap(index_, other->index_);
  swap(score_, other->score_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ForwardResponse_Label::GetMetadata() const {
  protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void ForwardResponse::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ForwardResponse::kCodeFieldNumber;
const int ForwardResponse::kMessageFieldNumber;
const int ForwardResponse::kBoxesFieldNumber;
const int ForwardResponse::kLabelFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ForwardResponse::ForwardResponse()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_forward_2eproto::scc_info_ForwardResponse.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:inference.wa.ForwardResponse)
}
ForwardResponse::ForwardResponse(const ForwardResponse& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      boxes_(from.boxes_),
      label_(from.label_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.message().size() > 0) {
    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  code_ = from.code_;
  // @@protoc_insertion_point(copy_constructor:inference.wa.ForwardResponse)
}

void ForwardResponse::SharedCtor() {
  message_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_ = 0;
}

ForwardResponse::~ForwardResponse() {
  // @@protoc_insertion_point(destructor:inference.wa.ForwardResponse)
  SharedDtor();
}

void ForwardResponse::SharedDtor() {
  message_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void ForwardResponse::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* ForwardResponse::descriptor() {
  ::protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const ForwardResponse& ForwardResponse::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_forward_2eproto::scc_info_ForwardResponse.base);
  return *internal_default_instance();
}


void ForwardResponse::Clear() {
// @@protoc_insertion_point(message_clear_start:inference.wa.ForwardResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  boxes_.Clear();
  label_.Clear();
  message_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_ = 0;
  _internal_metadata_.Clear();
}

bool ForwardResponse::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:inference.wa.ForwardResponse)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // int32 code = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(8u /* 8 & 0xFF */)) {

          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &code_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string message = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_message()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->message().data(), static_cast<int>(this->message().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "inference.wa.ForwardResponse.message"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .inference.wa.ForwardResponse.Box boxes = 5;
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_boxes()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated .inference.wa.ForwardResponse.Label label = 6;
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
                input, add_label()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:inference.wa.ForwardResponse)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:inference.wa.ForwardResponse)
  return false;
#undef DO_
}

void ForwardResponse::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:inference.wa.ForwardResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->code() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(1, this->code(), output);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "inference.wa.ForwardResponse.message");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->message(), output);
  }

  // repeated .inference.wa.ForwardResponse.Box boxes = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->boxes_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      5,
      this->boxes(static_cast<int>(i)),
      output);
  }

  // repeated .inference.wa.ForwardResponse.Label label = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->label_size()); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      6,
      this->label(static_cast<int>(i)),
      output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:inference.wa.ForwardResponse)
}

::google::protobuf::uint8* ForwardResponse::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:inference.wa.ForwardResponse)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // int32 code = 1;
  if (this->code() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(1, this->code(), target);
  }

  // string message = 2;
  if (this->message().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->message().data(), static_cast<int>(this->message().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "inference.wa.ForwardResponse.message");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->message(), target);
  }

  // repeated .inference.wa.ForwardResponse.Box boxes = 5;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->boxes_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        5, this->boxes(static_cast<int>(i)), deterministic, target);
  }

  // repeated .inference.wa.ForwardResponse.Label label = 6;
  for (unsigned int i = 0,
      n = static_cast<unsigned int>(this->label_size()); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        6, this->label(static_cast<int>(i)), deterministic, target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:inference.wa.ForwardResponse)
  return target;
}

size_t ForwardResponse::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:inference.wa.ForwardResponse)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated .inference.wa.ForwardResponse.Box boxes = 5;
  {
    unsigned int count = static_cast<unsigned int>(this->boxes_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->boxes(static_cast<int>(i)));
    }
  }

  // repeated .inference.wa.ForwardResponse.Label label = 6;
  {
    unsigned int count = static_cast<unsigned int>(this->label_size());
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          this->label(static_cast<int>(i)));
    }
  }

  // string message = 2;
  if (this->message().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->message());
  }

  // int32 code = 1;
  if (this->code() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::Int32Size(
        this->code());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void ForwardResponse::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:inference.wa.ForwardResponse)
  GOOGLE_DCHECK_NE(&from, this);
  const ForwardResponse* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ForwardResponse>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:inference.wa.ForwardResponse)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:inference.wa.ForwardResponse)
    MergeFrom(*source);
  }
}

void ForwardResponse::MergeFrom(const ForwardResponse& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:inference.wa.ForwardResponse)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  boxes_.MergeFrom(from.boxes_);
  label_.MergeFrom(from.label_);
  if (from.message().size() > 0) {

    message_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.message_);
  }
  if (from.code() != 0) {
    set_code(from.code());
  }
}

void ForwardResponse::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:inference.wa.ForwardResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ForwardResponse::CopyFrom(const ForwardResponse& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:inference.wa.ForwardResponse)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool ForwardResponse::IsInitialized() const {
  return true;
}

void ForwardResponse::Swap(ForwardResponse* other) {
  if (other == this) return;
  InternalSwap(other);
}
void ForwardResponse::InternalSwap(ForwardResponse* other) {
  using std::swap;
  CastToBase(&boxes_)->InternalSwap(CastToBase(&other->boxes_));
  CastToBase(&label_)->InternalSwap(CastToBase(&other->label_));
  message_.Swap(&other->message_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(code_, other->code_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata ForwardResponse::GetMetadata() const {
  protobuf_forward_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_forward_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace wa
}  // namespace inference
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::wa::ForwardRequest_Data* Arena::CreateMaybeMessage< ::inference::wa::ForwardRequest_Data >(Arena* arena) {
  return Arena::CreateInternal< ::inference::wa::ForwardRequest_Data >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::wa::ForwardRequest* Arena::CreateMaybeMessage< ::inference::wa::ForwardRequest >(Arena* arena) {
  return Arena::CreateInternal< ::inference::wa::ForwardRequest >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::wa::ForwardResponse_Box* Arena::CreateMaybeMessage< ::inference::wa::ForwardResponse_Box >(Arena* arena) {
  return Arena::CreateInternal< ::inference::wa::ForwardResponse_Box >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::wa::ForwardResponse_Label* Arena::CreateMaybeMessage< ::inference::wa::ForwardResponse_Label >(Arena* arena) {
  return Arena::CreateInternal< ::inference::wa::ForwardResponse_Label >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::inference::wa::ForwardResponse* Arena::CreateMaybeMessage< ::inference::wa::ForwardResponse >(Arena* arena) {
  return Arena::CreateInternal< ::inference::wa::ForwardResponse >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
