#!/usr/bin/env bash
set -ex
rm -rf evals
QBOXROOT=/Users/wangbing/QiNiuWordDir/qiniu_Github_Workshop
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/evals .
cp $QBOXROOT/ataraxia/inference/terror/python/terror-mixup/*.py evals/
mv evals/terror_mixup_infe.py  evals/eval.py

rm -rf build
mkdir build
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/inference/py build/
