MXNET_VERSION: mxnet
output_path: ./output/rfcn_dcn/rfcn_dcn-terror-v1.0-t1
symbol: resnet_v1_101_rfcn_dcn
gpus: '0'
CLASS_AGNOSTIC: true
SCALES:
  - 600
  - 1000
USE_GLOBAL_CONTEXT: false
default:
  frequent: 100
  kvstore: device
network:
  pretrained: ./model/pretrained_model/resnet_v1_101
  pretrained_epoch: 0
  PIXEL_MEANS:
    - 103.06
    - 115.9
    - 123.15
  IMAGE_STRIDE: 0
  RCNN_FEAT_STRIDE: 16
  RPN_FEAT_STRIDE: 16
  FIXED_PARAMS:
    - conv1
    - bn_conv1
    - res2
    - bn2
    - gamma
    - beta
  FIXED_PARAMS_SHARED:
    - conv1
    - bn_conv1
    - res2
    - bn2
    - res3
    - bn3
    - res4
    - bn4
    - gamma
    - beta
  ANCHOR_RATIOS:
    - 0.25
    - 0.5
    - 1
    - 2
    - 4
  ANCHOR_SCALES:
    - 2
    - 4
    - 8
    - 16
    - 32
  NUM_ANCHORS: 25
dataset:
  NUM_CLASSES: 11
  dataset: PascalVOC
  dataset_path: ./data/terror
  image_set: 2007_trainval
  root_path: ./data
  test_image_set: 2007_test
  proposal: rpn
TRAIN:
  lr: 0.0005
  lr_step: '9'
  warmup: true
  warmup_lr: 0.00005
  warmup_step: 3000
  begin_epoch: 0
  end_epoch: 14
  model_prefix: rfcn_voc
  RESUME: false
  FLIP: true
  SHUFFLE: true
  ENABLE_OHEM: true
  BATCH_IMAGES: 1
  END2END: true
  ASPECT_GROUPING: true
  BATCH_ROIS: -1
  BATCH_ROIS_OHEM: 256
  FG_FRACTION: 0.25
  FG_THRESH: 0.5
  BG_THRESH_HI: 0.5
  BG_THRESH_LO: 0
  BBOX_REGRESSION_THRESH: 0.5
  BBOX_WEIGHTS:
    - 1
    - 1
    - 1
    - 1
  RPN_BATCH_SIZE: 512
  RPN_FG_FRACTION: 0.5
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_NEGATIVE_OVERLAP: 0.3
  RPN_CLOBBER_POSITIVES: false
  RPN_BBOX_WEIGHTS:
    - 1
    - 1
    - 1
    - 1
  RPN_POSITIVE_WEIGHT: -1
  CXX_PROPOSAL: false
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 300
  RPN_MIN_SIZE: 0
  BBOX_NORMALIZATION_PRECOMPUTED: true
  BBOX_MEANS:
    - 0
    - 0
    - 0
    - 0
  BBOX_STDS:
    - 0.1
    - 0.1
    - 0.2
    - 0.2
TEST:
  HAS_RPN: true
  BATCH_IMAGES: 1
  CXX_PROPOSAL: true
  RPN_NMS_THRESH: 0.7
  RPN_PRE_NMS_TOP_N: 6000
  RPN_POST_NMS_TOP_N: 300
  RPN_MIN_SIZE: 0
  PROPOSAL_NMS_THRESH: 0.7
  PROPOSAL_PRE_NMS_TOP_N: 20000
  PROPOSAL_POST_NMS_TOP_N: 2000
  PROPOSAL_MIN_SIZE: 0
  NMS: 0.3
  BOX_VOTING_IOU_THRESH: 0.5
  BOX_VOTING_SCORE_THRESH: 0.1
  test_epoch: 0
