#!/usr/bin/env bash
set -ex

rm -rf evals
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/evals .
cp $QBOXROOT/ataraxia/inference/ocr/recognition/scene/python/main.py evals/eval.py
cp $QBOXROOT/ataraxia/inference/ocr/recognition/scene/python/test_eval.py evals/test_eval.py

#ln /dev/null /dev/raw1394

rm -rf src
cp -r $QBOXROOT/ataraxia/inference/ocr/recognition/scene/python src/

rm -rf build
mkdir build
cp -r $QBOXROOT/ataraxia/ava/atserving/scripts/inference/py build/
