argus-hack-watch: cd hack && exec ../../../../bin/argus-hack-watch -p 8557
face_group: cd hack && ENV=LOCAL CONFIG_HOSTS=localhost:2379 PORT_HTTP=7201 exec ../../../../bin/face_group -f ../cmd/face_group/face_group/face_group.conf
face_group_worker: cd hack && CONFIG_HOSTS=localhost:2379 PORT_HTTP=7202 exec ../../../../bin/face_group_worker -f ../cmd/face_group/face_group_worker/face_group_worker.conf
