#!/usr/bin/env bash
 
WORK_DIR=$PWD
CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
TARGET_DIR=${1}

if [ -f "${TARGET_DIR}/docker.build" ]; then
    ${TARGET_DIR}/docker.build ${@:2:$#-1}
    exit $?
fi

CMD1="${CURRENT_DIR}/docker-build"
${CMD1} -f ${TARGET_DIR}/template.Dockerfile ${@:2:$#-1}
