#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""image-label.

Usage:
  image-label PTS IMG1 IMG2
  image-label (-h | --help)
  image-label --version

Options:
  -h --help          Show this screen.
  --version          Show version.

"""
import os
from docopt import docopt
import cv2
import json


def main(arg):
    '''main'''

    img = cv2.imread(arg['IMG1'])
    pts = json.loads(arg['PTS'])
    for p in pts:
        cv2.rectangle(img,
                      (int(p[0][0]), int(p[0][1])),
                      (int(p[2][0]), int(p[2][1])),
                      (0, 255, 0), 3)
    cv2.imwrite(arg['IMG2'], img)


if __name__ == '__main__':

    os.chdir(os.path.dirname(os.path.realpath(__file__)))
    main(docopt(__doc__, version='0.5'))
