#!/usr/bin/env bash
set -ex

cur_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
generate_script="${cur_dir}/scripts/generate_app.py"
generate_integration_script="${cur_dir}/scripts/generate_integration_data.py"
tpl_basedir="${cur_dir}/templates/app"
package_name="qiniu.com/argus/cmd/argus-service"
out_basedir="${GOPATH}/src/${package_name}"

if [ -z "${APP_BUILD_CONF}" ]; then
    APP_BUILD_CONF="${GOPATH}/src/qiniu.com/argus/docker/argus-service/scripts/app.build.example.json"
fi

echo "generating app main and conf"
python ${generate_script} --app_build_conf_file="${APP_BUILD_CONF}" --app_tpl_dir="${tpl_basedir}" --app_out_dir="${out_basedir}"

licence_tags=""
if [ "${AVA_LICENCE}" == "true" ] ; then
    licence_tags="-tags=ava_licence"
fi

go install ${licence_tags} ${package_name} 
cp ${GOPATH}/bin/argus-service .